package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import sk.sav.bot.dataflos.entity.interf.AssociableEntity;

/**
 * Brumit2 generated by hbm2java
 */
@Entity
@Table(name = "brumit2")
public class Brumit2 implements java.io.Serializable, AssociableEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String meno;
    private String iso;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_parent")
    private Brumit1 brumit1;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "brumit2")
    private Set<Brumit3> brumit3s = new HashSet<>(0);

    public Brumit2() {
    }

    public Brumit2(Brumit1 brumit1, String meno) {
        this.brumit1 = brumit1;
        this.meno = meno;
    }

    public Brumit2(Brumit1 brumit1, String meno, String iso, Set<Brumit3> brumit3s) {
        this.brumit1 = brumit1;
        this.meno = meno;
        this.iso = iso;
        this.brumit3s = brumit3s;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Brumit1 getBrumit1() {
        return this.brumit1;
    }

    public void setBrumit1(Brumit1 brumit1) {
        this.brumit1 = brumit1;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public String getIso() {
        return this.iso;
    }

    public void setIso(String iso) {
        this.iso = iso;
    }

    public Set<Brumit3> getBrumit3s() {
        return this.brumit3s;
    }

    public void setBrumit3s(Set<Brumit3> brumit3s) {
        this.brumit3s = brumit3s;
    }

    @Override
    public String toString() {
        return this.iso + ", " + this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        String[] i = {"Iso", this.iso};
        String[] b = {"Brummitt 1", this.brumit1.getMeno(), "F Brumit1"};
        nAv.add(m);
        nAv.add(i);
        nAv.add(b);
        return nAv;
    }
}
