package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Brumit1 generated by hbm2java
 */
public class Brumit1 implements java.io.Serializable, Entity {

    private int id;
    private String meno;
    private Set brumit2s = new HashSet(0);

    public Brumit1() {
    }

    public Brumit1(String meno) {
        this.meno = meno;
    }

    public Brumit1(String meno, Set brumit2s) {
        this.meno = meno;
        this.brumit2s = brumit2s;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public Set getBrumit2s() {
        return this.brumit2s;
    }

    public void setBrumit2s(Set brumit2s) {
        this.brumit2s = brumit2s;
    }

    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        nAv.add(m);
        return nAv;
    }
}
