package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Ftgobvod generated by hbm2java
 */
public class Ftgobvod implements java.io.Serializable, Entity {

    private int id;
    private String meno;
    private String obvod;
    private Ftgoblast ftgoblast;
    private boolean schvalene;
    private Set ftgokreses = new HashSet(0);

    public Ftgobvod() {
    }

    public Ftgobvod(Ftgoblast ftgoblast, String obvod, String meno, boolean schvalene, Set ftgokreses) {
        this.ftgoblast = ftgoblast;
        this.obvod = obvod;
        this.meno = meno;
        this.schvalene = schvalene;
        this.ftgokreses = ftgokreses;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public Ftgoblast getFtgoblast() {
        return this.ftgoblast;
    }

    public void setFtgoblast(Ftgoblast ftgoblast) {
        this.ftgoblast = ftgoblast;
    }

    public String getObvod() {
        return this.obvod;
    }

    public void setObvod(String obvod) {
        this.obvod = obvod;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Set getFtgokreses() {
        return this.ftgokreses;
    }

    public void setFtgokreses(Set ftgokreses) {
        this.ftgokreses = ftgokreses;
    }

    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        String[] o = {"Obvod", this.obvod};
        String[] f = {"Ftg oblasť", this.ftgoblast == null ? "" : this.ftgoblast.getMeno(), "F Ftgoblast"};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(m);
        nAv.add(o);
        nAv.add(f);
        nAv.add(d);
        return nAv;
    }
}
