package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import sk.sav.bot.dataflos.entity.interf.AssociableEntity;

/**
 * Ftgobvod generated by hbm2java
 */
@Entity
@Table(name = "ftgobvod")
public class Ftgobvod implements java.io.Serializable, AssociableEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String meno;
    private String obvod;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_oblast")
    private Ftgoblast ftgoblast;
    
    private boolean schvalene;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ftgobvod")
    private Set<Ftgokres> ftgokreses = new HashSet<Ftgokres>(0);

    public Ftgobvod() {
    }

    public Ftgobvod(Ftgoblast ftgoblast, String obvod, String meno, boolean schvalene, Set<Ftgokres> ftgokreses) {
        this.ftgoblast = ftgoblast;
        this.obvod = obvod;
        this.meno = meno;
        this.schvalene = schvalene;
        this.ftgokreses = ftgokreses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Ftgoblast getFtgoblast() {
        return this.ftgoblast;
    }

    public void setFtgoblast(Ftgoblast ftgoblast) {
        this.ftgoblast = ftgoblast;
    }

    public String getObvod() {
        return this.obvod;
    }

    public void setObvod(String obvod) {
        this.obvod = obvod;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Set<Ftgokres> getFtgokreses() {
        return this.ftgokreses;
    }

    public void setFtgokreses(Set<Ftgokres> ftgokreses) {
        this.ftgokreses = ftgokreses;
    }

    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        String[] o = {"Obvod", this.obvod};
        String[] f = {"Ftg oblasť", this.ftgoblast == null ? "" : this.ftgoblast.getMeno(), "F Ftgoblast"};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(m);
        nAv.add(o);
        nAv.add(f);
        nAv.add(d);
        return nAv;
    }
}
