package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Genus generated by hbm2java
 */
public class Genus implements java.io.Serializable, Entity {

    private int id;
    private String meno;
    private String autor;
    private Family family;
    private FamilyApg familyApg;
    private boolean schvalene;
    private Set listOfSpecieses = new HashSet(0);
    private Set dallaTorres = new HashSet(0);

    public Genus() {
    }

    public Genus(FamilyApg familyApg, Family family, String meno, String autor, boolean schvalene, Set listOfSpecieses, Set dallaTorres) {
        this.familyApg = familyApg;
        this.family = family;
        this.meno = meno;
        this.autor = autor;
        this.schvalene = schvalene;
        this.listOfSpecieses = listOfSpecieses;
        this.dallaTorres = dallaTorres;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public FamilyApg getFamilyApg() {
        return this.familyApg;
    }

    public void setFamilyApg(FamilyApg familyApg) {
        this.familyApg = familyApg;
    }

    public Family getFamily() {
        return this.family;
    }

    public void setFamily(Family family) {
        this.family = family;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public String getAutor() {
        return this.autor;
    }

    public void setAutor(String autor) {
        this.autor = autor;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Set getListOfSpecieses() {
        return this.listOfSpecieses;
    }

    public void setListOfSpecieses(Set listOfSpecieses) {
        this.listOfSpecieses = listOfSpecieses;
    }

    public Set getDallaTorres() {
        return this.dallaTorres;
    }

    public void setDallaTorres(Set dallaTorres) {
        this.dallaTorres = dallaTorres;
    }
    
    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        String[] au = {"Autor", this.autor};
        String[] c = {"Čeľaď", this.family == null ? "" : this.family.getMeno(), "F Family"};
        String[] ap = {"Apg čeľaď", this.familyApg == null ? "" : this.familyApg.getMeno(), "F FamilyApg"};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(m);
        nAv.add(au);
        nAv.add(c);
        nAv.add(ap);
        nAv.add(d);
        return nAv;
    }
}
