package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Herbar generated by hbm2java
 */
public class Herbar implements java.io.Serializable, Entity {

    private int id;
    private String skratkaHerb;
    private String institucia;
    private boolean schvalene;
    private Set herbarPolozkies = new HashSet(0);

    public Herbar() {
    }

    public Herbar(String skratkaHerb, String institucia, boolean schvalene, Set herbarPolozkies) {
        this.skratkaHerb = skratkaHerb;
        this.institucia = institucia;
        this.schvalene = schvalene;
        this.herbarPolozkies = herbarPolozkies;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public String getSkratkaHerb() {
        return this.skratkaHerb;
    }

    public void setSkratkaHerb(String skratkaHerb) {
        this.skratkaHerb = skratkaHerb;
    }

    public String getInstitucia() {
        return this.institucia;
    }

    public void setInstitucia(String institucia) {
        this.institucia = institucia;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Set getHerbarPolozkies() {
        return this.herbarPolozkies;
    }

    public void setHerbarPolozkies(Set herbarPolozkies) {
        this.herbarPolozkies = herbarPolozkies;
    }

    @Override
    public String toString() {
        return this.skratkaHerb + ", " + this.institucia;
    }
    
    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] sk = {"Skratka herbára", this.skratkaHerb};
        String[] i = {"Inštitúcia", this.institucia};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(sk);
        nAv.add(i);
        nAv.add(d);
        return nAv;
    }
}
