package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import sk.sav.bot.dataflos.entity.interf.AssociableEntity;

/**
 * Kvadrant generated by hbm2java
 */
@Entity
@Table(name = "kvadrant")
public class Kvadrant implements java.io.Serializable, AssociableEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String typ;
    private String meno;
    private boolean schvalene;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "kvadrant")
    private Set<LokalityKvadrantAsoc> lokalityKvadrantAsocs = new HashSet<>(0);

    public Kvadrant() {
    }

    public Kvadrant(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Kvadrant(String meno, String typ, boolean schvalene, Set<LokalityKvadrantAsoc> lokalityKvadrantAsocs) {
        this.meno = meno;
        this.typ = typ;
        this.schvalene = schvalene;
        this.lokalityKvadrantAsocs = lokalityKvadrantAsocs;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public String getTyp() {
        return this.typ;
    }

    public void setTyp(String typ) {
        this.typ = typ;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

    public Set<LokalityKvadrantAsoc> getLokalityKvadrantAsocs() {
        return this.lokalityKvadrantAsocs;
    }

    public void setLokalityKvadrantAsocs(Set<LokalityKvadrantAsoc> lokalityKvadrantAsocs) {
        this.lokalityKvadrantAsocs = lokalityKvadrantAsocs;
    }

    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] t = {"Typ", this.typ};
        String[] m = {"Meno", this.meno};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(t);
        nAv.add(m);
        nAv.add(d);
        return nAv;
    }
}
