package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Embeddable;

/**
 * LokalityKvadrantAsocId generated by hbm2java
 */
@Embeddable
public class LokalityKvadrantAsocId  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
    private int idLokality;
    private int idKvadrant;

    public LokalityKvadrantAsocId() {
    }

    public LokalityKvadrantAsocId(int idLokality, int idKvadrant) {
       this.idLokality = idLokality;
       this.idKvadrant = idKvadrant;
    }
   
    public int getIdLokality() {
        return this.idLokality;
    }
    
    public void setIdLokality(int idLokality) {
        this.idLokality = idLokality;
    }
    public int getIdKvadrant() {
        return this.idKvadrant;
    }
    
    public void setIdKvadrant(int idKvadrant) {
        this.idKvadrant = idKvadrant;
    }

    @Override
    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LokalityKvadrantAsocId) ) return false;
		 LokalityKvadrantAsocId castOther = ( LokalityKvadrantAsocId ) other; 
         
		 return (this.getIdLokality()==castOther.getIdLokality())
				 && (this.getIdKvadrant()==castOther.getIdKvadrant());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLokality();
         result = 37 * result + this.getIdKvadrant();
         return result;
   }   


}


