package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * MenaZberRev generated by hbm2java
 */
public class MenaZberRev implements java.io.Serializable, Entity {

    private int id;
    private String meno;
    private String stdMeno;
    //private int uroven;
    private boolean schvalene;
    private Set udajZberAsocs = new HashSet(0);
    private Set skupRevDets = new HashSet(0);

    private Set lzdrojAutoriAsocs = new HashSet(0);
    private Set lzdrojEditoriAsocs = new HashSet(0);
    
    public MenaZberRev() {
    }

//    public MenaZberRev(int id, int uroven) {
//        this.id = id;
//        this.uroven = uroven;
//    }

    public MenaZberRev(int id, String meno, boolean schvalene,/* int uroven,*/ String stdMeno, Set udajZberAsocs, Set skupRevDets) {
        this.id = id;
        this.meno = meno;
        this.schvalene = schvalene;
        //this.uroven = uroven;
        this.stdMeno = stdMeno;
        this.udajZberAsocs = udajZberAsocs;
        this.skupRevDets = skupRevDets;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public String getMeno() {
        return this.meno;
    }

    public void setMeno(String meno) {
        this.meno = meno;
    }

    public boolean isSchvalene() {
        return this.schvalene;
    }

    public void setSchvalene(boolean schvalene) {
        this.schvalene = schvalene;
    }

//    public int getUroven() {
//        return this.uroven;
//    }
//
//    public void setUroven(int uroven) {
//        this.uroven = uroven;
//    }

    public String getStdMeno() {
        return this.stdMeno;
    }

    public void setStdMeno(String stdMeno) {
        this.stdMeno = stdMeno;
    }

    public Set getUdajZberAsocs() {
        return this.udajZberAsocs;
    }

    public void setUdajZberAsocs(Set udajZberAsocs) {
        this.udajZberAsocs = udajZberAsocs;
    }

    public Set getSkupRevDets() {
        return this.skupRevDets;
    }

    public void setSkupRevDets(Set skupRevDets) {
        this.skupRevDets = skupRevDets;
    }

    public Set getLzdrojAutoriAsocs() {
        return lzdrojAutoriAsocs;
    }

    public void setLzdrojAutoriAsocs(Set lzdrojAutoriAsocs) {
        this.lzdrojAutoriAsocs = lzdrojAutoriAsocs;
    }

    public Set getLzdrojEditoriAsocs() {
        return lzdrojEditoriAsocs;
    }

    public void setLzdrojEditoriAsocs(Set lzdrojEditoriAsocs) {
        this.lzdrojEditoriAsocs = lzdrojEditoriAsocs;
    }
    

    @Override
    public String toString() {
        return this.meno;
    }

    @Override
    public List<String[]> namesAndValues() {
        //List<Tuple<String, String>> nAv = new ArrayList<>();
        List<String[]> nAv = new ArrayList<>();
        String[] m = {"Meno", this.meno};
        String[] st = {"Štandardizované meno", this.stdMeno};
        //String[] u = {"Úroveň", String.valueOf(this.uroven)};
        String[] d = {"Schválené", this.schvalene == true ? "ano" : "nie"};
        nAv.add(m);
        nAv.add(st);
        //nAv.add(u);
        nAv.add(d);
        return nAv;
    }
}
