package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * MenaTaxonov generated by hbm2java
 */
public class MenaTaxonov implements java.io.Serializable, Entity {

    private int id;
    private ListOfSpecies listOfSpecies;
    private String menoScheda;
    private String poznamka;
    private Set skupRevs = new HashSet(0);

    public MenaTaxonov() {
    }

    public MenaTaxonov(ListOfSpecies listOfSpecies, String menoScheda, String poznamka, Set skupRevs) {
        this.listOfSpecies = listOfSpecies;
        this.menoScheda = menoScheda;
        this.poznamka = poznamka;
        this.skupRevs = skupRevs;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public ListOfSpecies getListOfSpecies() {
        return this.listOfSpecies;
    }

    public void setListOfSpecies(ListOfSpecies listOfSpecies) {
        this.listOfSpecies = listOfSpecies;
    }

    public String getMenoScheda() {
        return this.menoScheda;
    }

    public void setMenoScheda(String menoScheda) {
        this.menoScheda = menoScheda;
    }

    public String getPoznamka() {
        return this.poznamka;
    }

    public void setPoznamka(String poznamka) {
        this.poznamka = poznamka;
    }

    public Set getSkupRevs() {
        return this.skupRevs;
    }

    public void setSkupRevs(Set skupRevs) {
        this.skupRevs = skupRevs;
    }

    @Override
    public List<String[]> namesAndValues() {
        return null;
    }
    
    @Override
    public String toString() {
        return this.menoScheda;
    }

    public MenaTaxonov replicate() {
        MenaTaxonov mt = new MenaTaxonov();
        mt.setListOfSpecies(this.listOfSpecies);
        mt.setMenoScheda(this.menoScheda);
        mt.setPoznamka(this.poznamka);
        return mt;
    }
}
