package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.AssociableEntity;
import sk.sav.bot.dataflos.entity.interf.PeopleAsoc;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Table;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * SkupRev generated by hbm2java
 */
@Entity
@Table(name = "skup_rev")
public class SkupRev implements java.io.Serializable, AssociableEntity, Comparable<SkupRev> {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_udaj")
    private Udaj udaj;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_meno_rast_prirad")
    private MenaTaxonov menoTaxonu;
    
    private String datum;
    private boolean FRevizia;
    private String datumSlovom;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skupRev")
    private Set<PeopleAsoc> skupRevDets = new HashSet<>(0);

    public SkupRev() {
    }

    public SkupRev(Udaj udaj, MenaTaxonov menaTaxonu, String datum, boolean FRevizia, String datumSlovom) {
        this.udaj = udaj;
        this.menoTaxonu = menaTaxonu;
        this.datum = datum;
        this.FRevizia = FRevizia;
        this.datumSlovom = datumSlovom;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Udaj getUdaj() {
        return this.udaj;
    }

    public void setUdaj(Udaj udaj) {
        this.udaj = udaj;
    }

    public MenaTaxonov getMenaTaxonov() {
        return this.menoTaxonu;
    }

    public void setMenaTaxonov(MenaTaxonov menaTaxonov) {
        this.menoTaxonu = menaTaxonov;
    }

    public String getDatum() {
        return this.datum;
    }

    public void setDatum(String datum) {
        this.datum = datum;
    }

    public boolean isFRevizia() {
        return this.FRevizia;
    }

    public void setFRevizia(boolean FRevizia) {
        this.FRevizia = FRevizia;
    }

    public String getDatumSlovom() {
        return this.datumSlovom;
    }

    public void setDatumSlovom(String datumSlovom) {
        this.datumSlovom = datumSlovom;
    }

    public Set<PeopleAsoc> getSkupRevDets() {
        return this.skupRevDets;
    }

    public void setSkupRevDets(Set<PeopleAsoc> skupRevDets) {
        this.skupRevDets = skupRevDets;
    }

    @Override
    public String toString() {
        return this.datum;
    }

    @Override
    public List<String[]> namesAndValues() {
        return null;
    }

    @Override
    public int compareTo(SkupRev o) {
        return this.id - o.getId();
    }

    public SkupRev replicate() {
        MenaTaxonov mt = this.menoTaxonu.replicate();
        SkupRev rev = new SkupRev(null, mt, this.datum, this.FRevizia, this.datumSlovom);
        return rev;
    }
}
