package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * SkupRev generated by hbm2java
 */
public class SkupRev implements java.io.Serializable, Entity, Comparable<SkupRev> {

    private int id;
    private Udaj udaj;
    private MenaTaxonov menaTaxonov;
    private String datum;
    private boolean FRevizia;
    private String datumSlovom;
    private Set skupRevDets = new HashSet(0);

    public SkupRev() {
    }

    public SkupRev(Udaj udaj, MenaTaxonov menaTaxonov, String datum, boolean FRevizia, String datumSlovom) {
        this.udaj = udaj;
        this.menaTaxonov = menaTaxonov;
        this.datum = datum;
        this.FRevizia = FRevizia;
        this.datumSlovom = datumSlovom;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public Udaj getUdaj() {
        return this.udaj;
    }

    public void setUdaj(Udaj udaj) {
        this.udaj = udaj;
    }

    public MenaTaxonov getMenaTaxonov() {
        return this.menaTaxonov;
    }

    public void setMenaTaxonov(MenaTaxonov menaTaxonov) {
        this.menaTaxonov = menaTaxonov;
    }

    public String getDatum() {
        return this.datum;
    }

    public void setDatum(String datum) {
        this.datum = datum;
    }

    public boolean isFRevizia() {
        return this.FRevizia;
    }

    public void setFRevizia(boolean FRevizia) {
        this.FRevizia = FRevizia;
    }

    public String getDatumSlovom() {
        return this.datumSlovom;
    }

    public void setDatumSlovom(String datumSlovom) {
        this.datumSlovom = datumSlovom;
    }

    public Set getSkupRevDets() {
        return this.skupRevDets;
    }

    public void setSkupRevDets(Set skupRevDets) {
        this.skupRevDets = skupRevDets;
    }

    @Override
    public String toString() {
        return this.datum;
    }

    @Override
    public List<String[]> namesAndValues() {
        return null;
    }

    @Override
    public int compareTo(SkupRev o) {
        return this.id - o.getId();
    }

    public SkupRev replicate() {
        MenaTaxonov mt = this.menaTaxonov.replicate();
        SkupRev rev = new SkupRev(null, mt, this.datum, this.FRevizia, this.datumSlovom);
        return rev;
    }
}
