package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import sk.sav.bot.dataflos.entity.interf.PeopleAsoc;


/**
 * UdajZberAsoc generated by hbm2java
 */
@Entity
public class UdajZberAsoc implements java.io.Serializable, PeopleAsoc {

	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
    private UdajZberAsocId id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_udaj")
    private Udaj udaj;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_meno_zber")
    private MenaZberRev menaZberRev;
    
    private Integer poradie;

    public UdajZberAsoc() {
    }

    public UdajZberAsoc(Udaj udaj, MenaZberRev menaZberRev) {
        this.udaj = udaj;
        this.menaZberRev = menaZberRev;
    }

    public UdajZberAsoc(Udaj udaj, MenaZberRev menaZberRev, Integer poradie) {
        this.udaj = udaj;
        this.menaZberRev = menaZberRev;
        this.poradie = poradie;
    }

    public UdajZberAsocId getId() {
        return this.id;
    }

    public void setId(UdajZberAsocId id) {
        this.id = id;
    }

    public Udaj getUdaj() {
        return this.udaj;
    }

    public void setUdaj(Udaj udaj) {
        this.udaj = udaj;
    }

    @Override
    public MenaZberRev getMenaZberRev() {
        return this.menaZberRev;
    }

    public void setMenaZberRev(MenaZberRev menaZberRev) {
        this.menaZberRev = menaZberRev;
    }

    public Integer getPoradie() {
        return this.poradie;
    }

    @Override
    public void setPoradie(Integer poradie) {
        this.poradie = poradie;
    }

    @Override
    public String toString() {
        return this.menaZberRev.getMeno();
    }

}
