package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Embeddable;

/**
 * UdajZberAsocId generated by hbm2java
 */
@Embeddable
public class UdajZberAsocId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
    private int idUdaj;
    private int idMenoZber;

    public UdajZberAsocId() {
    }

    public UdajZberAsocId(int idUdaj, int idMenoZber) {
        this.idUdaj = idUdaj;
        this.idMenoZber = idMenoZber;
    }

    public int getIdUdaj() {
        return this.idUdaj;
    }

    public void setIdUdaj(int idUdaj) {
        this.idUdaj = idUdaj;
    }

    public int getIdMenoZber() {
        return this.idMenoZber;
    }

    public void setIdMenoZber(int idMenoZber) {
        this.idMenoZber = idMenoZber;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UdajZberAsocId)) {
            return false;
        }
        UdajZberAsocId castOther = (UdajZberAsocId) other;

        return (this.getIdUdaj() == castOther.getIdUdaj())
                && (this.getIdMenoZber() == castOther.getIdMenoZber());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdUdaj();
        result = 37 * result + this.getIdMenoZber();
        return result;
    }
}
