package sk.sav.bot.dataflos.entity;
// Generated May 30, 2012 11:34:04 AM by Hibernate Tools 3.2.1.GA

import sk.sav.bot.dataflos.entity.interf.Entity;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import sk.sav.bot.dataflos.util.ComparatorObr;

/**
 * Udaj generated by hbm2java
 */
public class Udaj implements java.io.Serializable, Entity {

    private int id;
    private LitZdroj litZdroj;
    private Lokality lokality;
    private HerbarPolozky herbarPolozky;
    private Character typ;
    private String datumZberu;
    private String stranaUdaja;
    private String datumZberuSlovom;
    private boolean verejnePristupny;
    private String verejnePristupnyOd;
    private String uzivatel;
    private Set skupRevs = new HashSet(0);
    private Set udajObrazkies = new HashSet(0);
    private Set udajZberAsocs = new HashSet(0);
    private Set litZdrojRevs = new HashSet(0);

    public Udaj() {
    }

    public Udaj(boolean verejnePristupny) {
        this.verejnePristupny = verejnePristupny;
    }

    public Udaj(LitZdroj litZdroj, Lokality lokality, HerbarPolozky herbarPolozky, Character typ, String datumZberu, String stranaUdaja, String datumZberuSlovom, boolean verejnePristupny, String uzivatel, Set skupRevs, Set udajObrazkies, Set udajZberAsocs) {
        this.litZdroj = litZdroj;
        this.lokality = lokality;
        this.herbarPolozky = herbarPolozky;
        this.typ = typ;
        this.datumZberu = datumZberu;
        this.stranaUdaja = stranaUdaja;
        this.datumZberuSlovom = datumZberuSlovom;
        this.verejnePristupny = verejnePristupny;
        this.uzivatel = uzivatel;
        this.skupRevs = skupRevs;
        this.udajObrazkies = udajObrazkies;
        this.udajZberAsocs = udajZberAsocs;
    }

    public int getId() {
        return this.id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public LitZdroj getLitZdroj() {
        return this.litZdroj;
    }

    public void setLitZdroj(LitZdroj litZdroj) {
        this.litZdroj = litZdroj;
    }

    public Lokality getLokality() {
        return this.lokality;
    }

    public void setLokality(Lokality lokality) {
        this.lokality = lokality;
    }

    public HerbarPolozky getHerbarPolozky() {
        return this.herbarPolozky;
    }

    public void setHerbarPolozky(HerbarPolozky herbarPolozky) {
        this.herbarPolozky = herbarPolozky;
    }

    public Character getTyp() {
        return this.typ;
    }

    public void setTyp(Character typ) {
        this.typ = typ;
    }

    public String getDatumZberu() {
        return this.datumZberu;
    }

    public void setDatumZberu(String datumZberu) {
        this.datumZberu = datumZberu;
    }

    public String getStranaUdaja() {
        return this.stranaUdaja;
    }

    public void setStranaUdaja(String stranaUdaja) {
        this.stranaUdaja = stranaUdaja;
    }

    public String getDatumZberuSlovom() {
        return this.datumZberuSlovom;
    }

    public void setDatumZberuSlovom(String datumZberuSlovom) {
        this.datumZberuSlovom = datumZberuSlovom;
    }

    public boolean isVerejnePristupny() {
        return this.verejnePristupny;
    }

    public void setVerejnePristupny(boolean verejnePristupny) {
        this.verejnePristupny = verejnePristupny;
    }
    
    public String getVerejnePristupnyOd() {
        return this.verejnePristupnyOd;
    }

    public void setVerejnePristupnyOd(String verejnePristupnyOd) {
        this.verejnePristupnyOd = verejnePristupnyOd;
    }
    
    public String getUzivatel() {
        return uzivatel;
    }

    public void setUzivatel(String uzivatel) {
        this.uzivatel = uzivatel;
    }

    public Set getSkupRevs() {
        return this.skupRevs;
    }

    public void setSkupRevs(Set skupRevs) {
        this.skupRevs = skupRevs;
    }

    public Set getUdajObrazkies() {
        return this.udajObrazkies;
    }

    public void setUdajObrazkies(Set udajObrazkies) {
        this.udajObrazkies = udajObrazkies;
    }

    public Set getUdajZberAsocs() {
        return this.udajZberAsocs;
    }

    public void setUdajZberAsocs(Set udajZberAsocs) {
        this.udajZberAsocs = udajZberAsocs;
    }

    public Set getLitZdrojRevs() {
        return litZdrojRevs;
    }

    public void setLitZdrojRevs(Set litZdrojRevs) {
        this.litZdrojRevs = litZdrojRevs;
    }
    
    public List<LitZdrojRev> getLitZdrojs() {
        List<LitZdrojRev> litZdrojs = new ArrayList<>();
        for (Object object : litZdrojRevs) {
            LitZdrojRev lzr = (LitZdrojRev) object;
            if (lzr.getLitZdroj() != null) {
                litZdrojs.add(lzr);
            }
        }
        return litZdrojs;
    }

    public SkupRev getUrcenie() {
        for (Object object : skupRevs) {
            SkupRev sr = (SkupRev) object;
            if (!sr.isFRevizia()) {
                return sr;
            }
        }
        return null;
    }

    public List<SkupRev> getRevisions() {
        List<SkupRev> revisions = new ArrayList<>();
        for (Object object : skupRevs) {
            SkupRev sr = (SkupRev) object;
            if (sr.isFRevizia()) {
                revisions.add(sr);
            }
        }
        return revisions;
    }
    
    public List<UdajObrazky> getObrazky() {
        List<UdajObrazky> obrazky = new ArrayList<>();
        for (Object object : udajObrazkies) {
            UdajObrazky obr = (UdajObrazky) object;
            obrazky.add(obr);
        }
        Collections.sort(obrazky, new ComparatorObr());
        return obrazky;
    }

    @Override
    public List<String[]> namesAndValues() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
